### ISSUE TITLE
when I run this command "sudo dpkg-buildpackage -b" I get this issue

### ISSUE THREAD

**Issue by ehsan0github** [mdfahadhossain/nginxQUIC#10]
../boringssl/include/openssl/span.h:115:36: error: ‘EnableIfContainer’ does not name a type
  115 |   template <typename C, typename = EnableIfContainer<C>,
      |                                    ^~~~~~~~~~~~~~~~~
../boringssl/include/openssl/span.h:115:53: error: expected ‘>’ before ‘<’ token
  115 |   template <typename C, typename = EnableIfContainer<C>,
      |                                                     ^
../boringssl/include/openssl/span.h:119:36: error: ‘EnableIfContainer’ does not name a type
  119 |   template <typename C, typename = EnableIfContainer<C>,
      |                                    ^~~~~~~~~~~~~~~~~
../boringssl/include/openssl/span.h:119:53: error: expected ‘>’ before ‘<’ token
  119 |   template <typename C, typename = EnableIfContainer<C>,
      |                                                     ^
make[2]: *** [objs/Makefile:2198: objs/addon/src/log_message_handler.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [objs/Makefile:2205: objs/addon/src/ngx_base_fetch.o] Error 1
make[2]: Leaving directory '/root/nginx/nginx-1.23.3/debian/build-nginx'
make[1]: *** [Makefile:10: build] Error 2
make[1]: Leaving directory '/root/nginx/nginx-1.23.3/debian/build-nginx'
make: *** [debian/rules:52: build-arch.nginx] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

what should I do for this?

**Comment by ehsan0github** [comment]
also previously, I get this error 
"./configure: error: invalid option "--with-http_quic_module"
make: *** [debian/rules:40: config.status.nginx] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2"
so I remove it "--with-http_quic_module" to correct it

**Comment by mdfahadhossain** [comment]
> also previously, I get this error "./configure: error: invalid option "--with-http_quic_module" make: *** [debian/rules:40: config.status.nginx] Error 1 dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2" so I remove it "--with-http_quic_module" to correct it

This should b fixed by the #11

**Comment by mdfahadhossain** [comment]
@ehsan0github please add more details.
